[project]
name = "ansible-module-tplink-wireless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ansible>=6.7.0",
    "playwright>=1.48.0",
]
